# Show the bar only on the specified output
outputs = { Targets = ["eDP-1"] }

# Which modules appear where in the status bar
[modules]
left = ["Clock"]
center = []
right = [["Mako", "Privacy", "Tray", "Settings"]]

# Clock display format
[clock]
format = " %a   %F   %R "

# Mako Do not Disturb toggle
[[CustomModule]]
name = "Mako"
icon = ""
command = "makoctl mode -t hide"
listen_cmd = "/home/jlk/.config/ashell/mako_status.sh"
icons.'hide.*' = ""
alert = ".*notifications"
